- src/main/python/keycodes.py
The current version of Vial does not support the DF keycode from QMK that allows you to change the current default layer. It should probably exist and works just fine in the firmware.
Therefore this PR proposes the change to add the keycode to the mapping.
Before:
After:
> Add DF keycode support

- requirements.txt
- src/main/python/keyboard_comm.py
- src/main/python/keyboard_widget.py
- src/main/python/main_window.py
- src/main/python/matrix_test.py
Since the matrix test is something I need use a lot, and I like using VIAL.
I've reversed the disabling of the matrix test feature in VIAL and locked it behind the lock feature in VIAL.
I've also increased the VIAL protocol version, so the Gui can distinguish boards that do and don't support the new implementation.
This PR goes in tandem with A PR that implements a tester in Vial-QMK, see: https://github.com/vial-kb/vial-qmk/pull/8
In regards to issue: vial-kb/vial-gui#23
> Matrix tester

- src/main/python/matrix_test.py
I Found a bug in the matrix_test code that causes the application to throw an error when trying to test a board with a vial encoder.
This is due to encoders not having matrix positions.
I added a check to make sure this does not happen anymore.
> fix: Fixed bug that crashes matrix_text when encoders are present

- src/main/python/keyboard_comm.py
- src/main/python/keycodes.py
- src/main/python/keymap_editor.py
- src/main/python/square_button.py
- src/main/python/tabbed_keycodes.py
I've added some code to allow you to define custom keycodes in the vial.json
For the format I've made use of the customKeycode schema in use in VIA.
The most thorough documentation I found on this was https://github.com/jjesuscastro/qmk_firmware/tree/master/keyboards/kbdfans/kbd67/rev2/keymaps/jjesuscastrol
To account for long keycode descriptors I've added automatic wrap functionality to SquareButton, which can be turned on with SquareButton.setWordWrap(True)
Hope this is usefull.
I'm open to feedback
Keyboard/keymap used for testing
https://github.com/Pieterv24/vial-qmk/tree/keyboards/keyboards/handwired/pieterv24/bento/keymaps/deej
> Added custom keycode functionality

- src/main/python/basic_editor.py
- src/main/python/editor_container.py
- src/main/python/keymap_editor.py
- src/main/python/main_window.py
Small UI change to allow the deselection of a currently-selected key in the keymap editor when the editor's container is clicked.
- Adds an EditorContainer to handle mouse click events on an editor's container widget.
- Adds a handler for container mouse click events to KeymapEditor to deselect and cancel a key selection.
> Deselect key in keymap editor when container is clicked

- src/main/python/keymap_editor.py
Turns out that the `mousePressEvent` handler in KeymapEditor isn't needed with the handler in the container.
> Clean up mousePressEvent handler from KeymapEditor

- src/main/python/keyboard_comm.py
- src/main/python/keycodes.py
- src/main/python/tabbed_keycodes.py
To use this you've to add MIDI_ENABLE = yes to rules.mk, #define MIDI_BASIC or #define MIDI_ADVANCED to config.h & "vial": { "midi": "basic" }, or "vial": { "midi": "advanced" }, to vial.json
> Added MIDI tab & keycodes

- src/main/python/main_window.py
Add the following keyboard shortcuts:
* Ctrl/Cmd + U — **U**nlock
* Ctrl/Cmd + L — **L**ock
* Ctrl/Cmd + B\* — Reboot to **b**ootloader
\* “B” was selected rather than “R” since users in the process of switching from QWERTY to Colemak are likely to accidentally hit Ctrl+R when they meant Ctrl+S, and this could cause data loss.
> Add security menu shortcuts

- src/main/python/editor/macro_recorder.py
Moved the generation of the macro_tab_w to *rebuild()*
This was to be able to generate it `DYNAMIC_KEYMAP_MACRO_COUNT` big instead of a fixed 32
It has been tested with different macro_counts from 1 to 109.
> Increased possible macros

- src/main/python/keymap/brazilian.py
- src/main/python/keymaps.py
Adding Brazilian "ABNT2" keymap.
I could only test in windows, but this shouldn't have any OS specific issue, right?
> Brazilian Keymap

- src/main/python/macro/macro_recorder_linux.py
- src/main/python/macro/macro_recorder_windows.py
`QtWidget.move()` expects integers when called with x and y coordinates. I'm not sure what changed from Python 3.6 and Qt 5.9 to Python 3.10 and Qt 5.15, but forcibly rounding here works regardless of version.
> refactor: deliberately round "Stop recording" x position

- src/main/python/editor/keymap_editor.py
- src/main/python/keycodes/keycodes.py
- src/main/python/protocol/keyboard_comm.py
- src/main/python/protocol/macro.py
- src/main/python/tabbed_keycodes.py
- src/main/python/widgets/key_widget.py
Issues resolved:
- Boards with encoders throw errors and can't be mapped
- `Any` throws errors if you try to assign it from the keycode list (double-clicking a key in the keyboard layout works)
- Nested keycodes cannot be assigned in non-layout pages (e.g. combos)
- Macros with delays weren't being deserialized correctly (It felt very dumb to open up a separate PR for basically one line.)
> fix: encoders, macro rendering, some keycode handling

- src/main/python/main.py
- src/main/python/main_window.py
- Sets `WM_CLASS` for the application. This attribute gives various X window managers (bspwm, i3, etc) more out of the box control over how windows display. Subclassing `ApplicationContext` might seem like overkill, but given the `@cached_property` decorator in `fbs` I don't think there's another way. (Yes, `appctx.app.setApplicationName()` was the first thing I tried.)
- [This is also where `applicationVersion` is set](https://github.com/mherrmann/fbs/blob/702761412a2c8617e68ea8c398f7df725ef71a79/fbs_runtime/application_context/__init__.py#L55), so to further reduce the surface area exposed to `fbs`, the `build_settings` lookup in `main_window.py` was replaced with Qt's standard attribute.
- Closes #175: when re-opening Vial, checks that no part of the application would be offscreen …
> feat: improvements to main window

- src/main/python/editor/key_override.py
I found it tedious when adding a Key Override to a single layer to have so go through and disable all the other layers. Reverting back to all layers was similarly fiddly.
To address this, small “Enable all” and “Enable none” buttons have been added beneath the list of layers to which a Key Override applies. Clicking the buttons will, as expected, enable or disable all the layer check boxes.
Tested that:
* Clicking “Enable none“ deactivated all the “Enable on layers” checkboxes on the Key Override settings tab
* Clicking “Enable all” activated all the “Enable on layers” checkboxes.
* Checked that “Enable none“ had the expected behaviour on five layers of a keyboard
* Checked that “Enable all“ had the expected behaviour on five layers of a keyboard
> Quick Toggle Key Override Layers

- src/main/python/keymap/japanese.py
- src/main/python/keymaps.py
This PR adds JIS layouts for Japanese.
https://en.wikipedia.org/wiki/Keyboard_layout#Japanese
> keymap: add JIS (japanese) keymap

- src/main/python/main_window.py
This improves the user experience when the window was maximized during the last run (tested on Windows)
> Restore whether the window was maximized in the last run

- src/main/python/keymap/eurkey.py
- src/main/python/keymap/us_international.py
- src/main/python/keymaps.py
> keymaps: Add US International, Fix unescaped backslash in eurkey.py

- src/main/python/keycodes/keycodes_v5.py
From vial-kb/vial-gui#318
Same change in v6 copied over to v5 keycodes script, this prevents a similar crash that would still happen sometimes if it's using the v5 version.
Also added a TODO comment about it.
> Increased user keycodes limit in keycodes_v5

- src/main/python/keycodes/keycodes.py
- src/main/python/keycodes/keycodes_v5.py
- src/main/python/keycodes/keycodes_v6.py
Renames `RESET`/`QK_BOOT` to `Bootloader`, adds `Reboot`/`QK_REBOOT` and `Clear EEPROM`/`QK_CLEAR_EEPROM`
> Update Quantum Keycodes

- src/main/python/about_keyboard.py
- src/main/python/keycodes/keycodes.py
- src/main/python/keycodes/keycodes_v5.py
- src/main/python/keycodes/keycodes_v6.py
- src/main/python/protocol/constants.py
- src/main/python/protocol/dummy_keyboard.py
- src/main/python/protocol/dynamic.py
- src/main/python/tabbed_keycodes.py
- src/main/python/test/test_gui.py
- src/main/python/test/test_keycode.py
As discussed [in this thread](https://github.com/vial-kb/vial-gui/issues/302), this PR adds GUI changes for QMK's `PDF(layer)` switches, [Caps Word](https://docs.qmk.fm/features/caps_word) and [Layer Lock](https://docs.qmk.fm/features/layer_lock) to vial-gui.
The corresponding Vial firmware change is in https://github.com/vial-kb/vial-qmk/pull/902
Details:
* The last bits of the response to `DYNAMIC_VIAL_GET_NUMBER_OF_ENTRIES` indicate optionally supported features. A `.supported_features` set field in `ProtocolDynamic` remembers which feature bits were set.
* Added a `requires_feature` field to `Keycode` to note when the keycode depends on an optional feature. These keycodes are only shown if the required feature is supported.
* Bumped the Vial protocol version (5 → 6).
Screenshots to …
> PDF(layer), Caps Word, and Layer Lock for vial-gui.
